-- MySQL Script generated by MySQL Workbench
-- Mon Sep  7 00:36:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema profesores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema profesores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `profesores` DEFAULT CHARACTER SET utf8 ;
USE `profesores` ;

-- -----------------------------------------------------
-- Table `profesores`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesores`.`profesores` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profesores`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesores`.`materias` (
  `idmateria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `profesor` INT NOT NULL,
  PRIMARY KEY (`idmateria`),
  CONSTRAINT `profesor_FK`
    FOREIGN KEY (`profesor`)
    REFERENCES `profesores`.`profesores` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `profesor_FK_idx` ON `profesores`.`materias` (`profesor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
